<a href="https://colab.research.google.com/github/just1nseo/YBIGTA/blob/main/%ED%86%B5%EA%B3%84%EA%B8%B0%EC%B4%88_%ED%9A%8C%EA%B7%80%EB%B6%84%EC%84%9D_%EA%B3%BC%EC%A0%9C_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 22기 교육세션 [통계기초, 회귀분석] 과제

### 선형 회귀분석에서 쓰이는 **정규방정식**을 행렬로 구현하고, sklearn 혹은 OLS 패키지를 통해 구한 **실제 값과 비교**해주세요.

#### 데이터 불러오기

In [2]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd 
data = pd.read_csv('/content/drive/MyDrive/assignment.csv')

Mounted at /content/drive


In [3]:
data.head()

y    x1    x2  x3   x4    x5
0  10  38.9  64.7   4  868  59.7
1  13  41.6  45.3  -4  957  61.4
2  11  39.7  74.1   8  786  61.0
3   7  37.3  48.0  19  984  67.5
4  10  39.5  51.9   6  700  57.2

In [4]:
data.shape     # y:(9,1), X:(9,5)

(9, 6)

In [5]:
X = data.drop(["y"], axis=1)
y = data.y

In [6]:
# Matrix 계산을 위해 X와 y를 numpy 형태로 바꾸어줍니다. 
X = X.to_numpy()
y = y.to_numpy()

In [7]:
X

array([[  38.9,   64.7,    4. ,  868. ,   59.7],
       [  41.6,   45.3,   -4. ,  957. ,   61.4],
       [  39.7,   74.1,    8. ,  786. ,   61. ],
       [  37.3,   48. ,   19. ,  984. ,   67.5],
       [  39.5,   51.9,    6. ,  700. ,   57.2],
       [  37.4,   53.6,   -5. , 1037. ,   58.8],
       [  35.1,   71.4,    3. ,  986. ,   58.6],
       [  38.8,   58.3,    6. ,  819. ,   59.2],
       [  36.6,   52.6,  -19. ,  791. ,   54.4]])

In [8]:
y

array([10, 13, 11,  7, 10,  9,  9,  6,  5])

#### 정규방정식

In [9]:
import numpy as np
from numpy.linalg import inv 

In [13]:
def estimate_beta(X, y):
    
    designX = np.column_stack((np.ones(X.shape[0]), X))
    beta_hat = np.linalg.inv(np.dot(designX.T, designX)).dot(designX.T).dot(y)
    
    return beta_hat

In [14]:
beta_hat = estimate_beta(X, y)
beta_hat

array([-3.92447368e+01,  1.31232583e+00,  8.53744361e-02,  7.41849897e-02,
        1.50018573e-02, -3.42273652e-01])

#### 실제 값과 비교

In [15]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [28]:
model = LinearRegression()
model.fit(X, y)


LinearRegression()

In [29]:
print(model.intercept_)   # intercept
print(model.coef_)   # 추정된 회귀계수 (intercept 제외)

-39.24473678135655
[ 1.31232583  0.08537444  0.07418499  0.01500186 -0.34227365]
